datasets:
  ds005602: 
    bids_dir: '/localscratch/ds005602'


#this configures the pybids grabber - create an entry for each type of input you want to grab
# indexed by name of input
#   dictionary for each input is passed directly to pybids get()
#    https://bids-standard.github.io/pybids/generated/bids.layout.BIDSLayout.html#bids.layout.BIDSLayout.get

defaults:


  pybids_inputs:  #can be overriden in the dataset
    t1:
      filters:
        suffix: 'T1w'
        extension: '.nii.gz'
        datatype: 'anat'
        subject: 
          - '1'
          - '11'
          - '12'
          - '13'
          - '14'
          - '15'
          
      wildcards:
        - subject
        - session
        - acquisition
        - run



  #this configures the options to save the BIDSLayout
  # by default, database is not saved (uncomment to save)
  # NOTE: pybids_db_dir must be an absolute path
  # pybids_db_dir: '/path/to/db_dir' # Leave blank if you do not wish to use this
  # pybids_db_reset: False # Change this to true to update the database


  derivatives: False #will search in bids/derivatives if True; can also be path(s) to derivatives datasets - can be overriden in datasets

  singularity_prefix: '/cifs/khan/shared/containers/snakemake_containers/' #'/project/6050199/akhanf/singularity/snakemake_containers' #can be overriden in apps

  resources:  # can be overriden in apps
    cores: 8
    mem_mb: 32000
    runtime: 360 
    tmpdir: /tmp
    gpus: 0

  tmpdir_env: SLURM_TMPDIR  



# app options below:

apps_to_run:
  snakedwi:
    name: snakedwi
    version: v0.2.0-alpha
    args: "{input} {output} participant"

  hippunfold:
    name: hippunfold
    version: 'v1.4.1'
    args: ""


#  scattr:
#    bids_dir: '{dataset}/derivatives/snakeanat'
#    snakebids: True
#    url: 'http://github.com/akhanf/scattr'
#    tag: 'new-snakedwi'
#    runscript: 'scattr/run.py' #relative to the app repo
#    depends_on:
#      - snakeanat
#      - snakedwi
#    singularity_opts: '-e'
#    shadow: null
#    opts: '--filter-T1w desc=preproc space=T1w  --freesurfer_dir {dataset}/derivatives/snakeanat/sourcedata/fastsurfer_surf --dwi_dir {dataset}/snakedwi/snakedwi --profile cc-slurm'
#    retain_subj_dirs_from: 
#      - 'mrtrix'
#      - 'labelmerge'
#    input_to_filter: dwi #e.g. for --filter-dwi
#    resources:
#      cores: 1
#      mem_mb: 4000
#      runtime: 1440
#      gpus: 0


