datasets:
  LOBE: 
    bids_dir: '/project/6050199/akhanf/cfmm-bids/data/Khan/LOBE/raw/baseline/bids'

output_dir: 'results'

derivatives: False #will search in bids/derivatives if True; can also be path(s) to derivatives datasets

#list of analysis levels in the bids app
analysis_levels: &analysis_levels
 - participant


#mapping from analysis_level to set of target rules or files
targets_by_analysis_level:
  participant:
    - ''  # if '', then the first rule is run

#this configures the pybids grabber - create an entry for each type of input you want to grab
# indexed by name of input
#   dictionary for each input is passed directly to pybids get()
#    https://bids-standard.github.io/pybids/generated/bids.layout.BIDSLayout.html#bids.layout.BIDSLayout.get

pybids_inputs:
  dwi:
    filters:
      suffix: 'dwi'
      extension: '.nii.gz'
      datatype: 'dwi'
    wildcards:
      - subject
      - session
      - acquisition
      - run
      - direction
  t1:
    filters:
      suffix: 'T1w'
      extension: '.nii.gz'
      datatype: 'anat'
    wildcards:
      - subject
      - session
      - acquisition
      - run


#this configures the options to save the BIDSLayout
# by default, database is not saved (uncomment to save)
# NOTE: pybids_db_dir must be an absolute path
# pybids_db_dir: '/path/to/db_dir' # Leave blank if you do not wish to use this
# pybids_db_reset: False # Change this to true to update the database

#configuration for the command-line parameters to make available
# passed on the argparse add_argument()
parse_args:

#---  core BIDS-app options --- (do not modify below)

  bids_dir:
    help: The directory with the input dataset formatted according
          to the BIDS standard.

  output_dir:
    help: The directory where the output files
          should be stored. If you are running group level analysis
          this folder should be prepopulated with the results of the
          participant level analysis.

  analysis_level:
    help: Level of the analysis that will be performed.
    choices: *analysis_levels

  --participant_label:
    help: The label(s) of the participant(s) that should be analyzed. The label
          corresponds to sub-<participant_label> from the BIDS spec
          (so it does not include "sub-"). If this parameter is not
          provided all subjects should be analyzed. Multiple
          participants can be specified with a space separated list.
    nargs: '+'

  --exclude_participant_label:
    help: The label(s) of the participant(s) that should be excluded. The label
          corresponds to sub-<participant_label> from the BIDS spec
          (so it does not include "sub-"). If this parameter is not
          provided all subjects should be analyzed. Multiple
          participants can be specified with a space separated list.
    nargs: '+'

  --derivatives:
    help: 'Path(s) to a derivatives dataset, for folder(s) that contains multiple derivatives datasets (default: %(default)s) '
    default: False
    nargs: '+'


singularity_prefix: '/project/6050199/akhanf/singularity/snakemake_containers'

# app options below:

apps:
  snakedwi:
    snakebids: True
    url: 'http://github.com/akhanf/snakedwi'
    tag: 'v0.2.0-alpha'
    runscript: 'snakedwi/run.py' #relative to the app repo
    opts: ''
    retain_subj_dirs_from:
      - 'snakedwi'
    input_to_filter: dwi #e.g. for --filter-dw
    singularity_opts: '--nv'
    resources:
      cores: 8
      mem_mb: 32000
      runtime: 360 
      gpus: 1

  snakeanat:
    snakebids: True
    url: 'http://github.com/akhanf/snakeanat'
    tag: 'updates'
    runscript: 'snakeanat/run.py' #relative to the app repo
    opts: '--use-envmodules'
    retain_subj_dirs_from:
      - ''
      - 'sourcedata/ciftify'
      - 'sourcedata/fastsurfer'
      - 'sourcedata/fastsurfer_surf'
      - 'qc'
    input_to_filter: t1 #e.g. for --filter-dwi
    resources:
      cores: 8
      mem_mb: 16000
      runtime: 720
      gpus: 0


  hippunfold:
    snakebids: True
    container: 'docker://khanlab/hippunfold:v1.3.3.sif'
    opts: '--modality T1w --keep-work --generate-myelin-map'
    retain_subj_dirs_from:
      - 'hippunfold'
      - 'work' #remove this if --keep-work not used
    input_to_filter: t1 #e.g. for --filter-dwi
    resources:
      cores: 8
      mem_mb: 32000
      runtime: 360 
      gpus: 0

  fmriprep:
    container: '/project/6050199/akhanf/singularity/bids-apps/nipreps_fmriprep_23.1.0.sif'
    depends_on:
      - snakeanat
    singularity_opts: '-e'
    opts: '--fs-subjects-dir {dataset}/snakeanat/sourcedata/fastsurfer_surf'
    retain_subj_dirs_from: #no way to save html files as of yet..
      - ''
    retain_files: #relative to output folder
      - 'sub-{subject}.html'
    input_to_filter: t1 #e.g. for --filter-dwi
    resources:
      cores: 8
      mem_mb: 32000
      runtime: 360 
      gpus: 0

  scattr:
    bids_dir: '{dataset}/snakeanat'
    snakebids: True
    url: 'http://github.com/akhanf/scattr'
    tag: 'new-snakedwi'
    runscript: 'scattr/run.py' #relative to the app repo
    depends_on:
      - snakeanat
      - snakedwi
    singularity_opts: '-e'
    shadow: null
    opts: '--filter-T1w desc=preproc space=T1w  --freesurfer_dir {dataset}/snakeanat/sourcedata/fastsurfer_surf --dwi_dir {dataset}/snakedwi/snakedwi --profile cc-slurm'
    retain_subj_dirs_from: #no way to save html files as of yet..
      - 'mrtrix'
      - 'labelmerge'
    input_to_filter: dwi #e.g. for --filter-dwi
    resources:
      cores: 1
      mem_mb: 4000
      runtime: 1440
      gpus: 0


default_resources:  #uses these if not specified in app
  cores: 8
  mem_mb: 32000
  runtime: 360 
  tmpdir: /tmp
  gpus: 0

tmpdir_env: SLURM_TMPDIR  
shadow: 'minimal'
